services:
  - type: web
    name: football-actuel-gabon
    env: docker
    plan: free
    publishPath: public
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        sync: false
      - key: APP_URL
        value: https://actu-football-gabon.onrender.com
      - key: LOG_CHANNEL
        value: errorlog
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_DRIVER
        value: file
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: actufootgabon
          property: host
      - key: DB_DATABASE
        fromDatabase:
          name: actufootgabon
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: actufootgabon
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: actufootgabon
          property: password

databases:
  - name: actufootgabon
    databaseName: laravel
    user: actufootgabon_user
